import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useState } from "react"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
	const [selectedFile, setselectedFile] = useState<File | null>(null)
	const [result, setresult] = useState("")
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>file upload</h1>
				<div>
					<input
						type="file"
						onChange={(event) => {
							setselectedFile(
								event.target?.files ? event.target?.files[0] : null
							)
						}}
					/>
					<button
						onClick={() => {
							if (selectedFile) {
								// Create an object of formData
								const formData = new FormData()

								// Update the formData object
								formData.append("theFiles", selectedFile)

								const options = {
									method: "POST",
									body: formData,
								}

								fetch("/api/upload", options)
									.then((response) => response.json())
									.then((response) => {
										console.log(response)
										setresult(response.result.Key)
									})
									.catch((err) => console.error(err))
							}
						}}
					>
						Upload!
					</button>
				</div>

				<br />

				<div>
					Key:{" "}
					<span
						onClick={() => {
							window.open("/api/get?id=" + result)
						}}
					>
						{result}
					</span>{" "}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Home
